### ISSUE TITLE
[Inclusion Requests]: New Tailwind CSS Components for React UI Library 

### ISSUE THREAD

**Issue by ZissyW** [officialrajdeepsingh/awesome-nextjs#22]
**Good day Rajdeep!**

I would also like introduce you to our own tailwind library: https://tailsc.com/. Tailsc focuses on stylish, accessible and free UI components that you can just copy & paste on any tailwind css project.

Your review would be invaluable, and if My project can resonates with you, I’d be thrilled to see it as part of your highlighted libraries.

**Comment by officialrajdeepsingh** [comment]
hi @ZissyW 
please create pull with [tailsc.com](https://tailsc.com/).
